name: flutter_note_mate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1

  firebase_core: ^2.32.0

  flutter_screenutil: ^5.9.3
  # Pin code input (OTP) text field
  pinput: ^5.0.0

  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  build_runner: ^2.4.7

  firebase_auth: ^4.20.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash/splash.png
    - assets/splash/splash_dark.png
    - assets/auth/image/
    - assets/image/home/
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Regular.ttf
        - asset: assets/font/Nunito-Bold.ttf
          weight: 700
        - asset: assets/font/Nunito-Italic.ttf
          style: italic
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:

  color: "#ffffff"
  image: assets/splash/splash.png

  image_dark: assets/splash/splash_dark.png
  color_dark: "#041128"

  android_12:

    image: assets/splash/splash.png
    color: "#ffffff"

    image_dark: assets/splash/splash_dark.png
    color_dark: "#041128"


